### ISSUE TITLE
Unable to change email, OTP verification fails. "User not found"

### ISSUE THREAD

**Issue by loyoliteabid** [supabase/auth-js#798] opened 2023-10-16 06:40 UTC
# Bug report
 When a signed user attempts to change their email address. OTP receives to the new email. however when we try to verifyOtp I get an error saying "User not found". This is happening only when we try to change email using type: email_change. other types like signup are working fine.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Signup using email 
2. Login using email and password
3. change email using 
   `const { data, error } = await supabase.auth.updateUser({ email });`
4. Verify otp using 
   `const { data, error } = await supabase.auth.verifyOtp({
      token: otp,
      type: "email_change",
      email, /* new email */
    });`
5. See error
 `{"name":"AuthApiError","message":"User not found","status":404}`

## Expected behavior
Signed user should be able to change their email with OTP verification

## System information

-Browser  chrome
- "@supabase/auth-helpers-nextjs": "latest",
- "@supabase/supabase-js": "latest",

**Comment by abiddraws** [comment] 2023-10-18 14:55
@canardos , I am utilizing Spabase Cloud rather than a local CLI. Nevertheless, when attempting your solution, I encountered the following error message:
`{"name":"AuthApiError","message":"Verify requires either a token or a token hash","status":400}`

code: 
```
const handleVerifyOTP = async (e: React.MouseEvent<HTMLButtonElement>) => {
    console.log("Call receives...");
    e.preventDefault();
    e.stopPropagation();

    const text = email + otp //'your data to hash';
    const encoder = new TextEncoder();
    const bufferText = encoder.encode(text);
    const buf = await window.crypto.subtle.digest("SHA-256", bufferText);
    const tokenHash = Array.from(new Uint8Array(buf))
      .map((item) => item.toString(16).padStart(2, "0"))
      .join("");

    const { data, error } = await supabase.auth.verifyOtp({
      token: otp,
      type: "email",
      email,
      token_hash: tokenHash,
    });

    if (error) {
      console.log(JSON.stringify(error));
    }
    if (data?.user) {
      alert(`OTP ${otp} verified successfully!`);
    }
  };
```

It expects either a "token" or a "token_hash."

The issue arises when I attempt to change my email using the OTP option. When I use the link method, it functions as expected. I want to emphasize that I am certain I'm entering the correct OTP, as I've attempted it multiple times.

I am using latest version of the library
```
 "dependencies": {
    "@supabase/auth-helpers-nextjs": "latest",
    "@supabase/supabase-js": "latest",
    "autoprefixer": "10.4.15",
    "next": "latest",
    "postcss": "8.4.29",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.3",
    "typescript": "5.1.3"
  },
  ```

**Comment by canardos** [comment] 2023-10-18 15:35
`Verify requires either a token or a token hash` is the [expected behavior](https://github.com/supabase/gotrue/blob/40aed622f24066b2718e4509a001026fe7d4b76d/internal/api/verify.go#L70C3-L72C4) when providing both the `token` and `token_hash`. I only had to provide both as I was using a version prior to [this commit](https://github.com/supabase/gotrue/commit/e9ab55559f7e5e62f7a56005347993e4e9da527b).

Given you're on the latest version, I suspect you have a different issue. You could try with the `token_hash` only, or use it to manually compare again the hash in the `auth.users` table, but I can't see it helping.

**Comment by abiddraws** [comment] 2023-10-19 03:13
if I try with `token_hash` only , i get this error 
`{"name":"AuthApiError","message":"Database error finding user from email link","status":500}` 
:(

**Comment by canardos** [comment] 2023-10-19 06:26
Apologies, but my earlier code had the wrong algo (I'm using node and copied/adjusted for the browser). It [should be SHA-224](https://github.com/supabase/gotrue/blob/master/internal/crypto/crypto.go#L41). I don't think SHA-224 is supported in the browser, but you can easily just [calculate it manually here](https://www.tools4noobs.com/online_tools/hash/) and see if it matches the hash in the `auth.users` table. Or you could use a lib.

Also, you have `type: "email"`, but is should be `type: "email_change"`

Finally, if you're providing the `token_hash`, then on the latest version I think you should only provide `type` and `token_hash`.

**Comment by kangmingtay** [comment] 2023-10-19 14:10
@abiddraws can you please send us a support ticket at https://supabase.com/dashboard/support/new ? it will be much easier for us to figure out what went wrong here with your project details!

**Comment by saousername** [comment] 2024-01-18 18:37
for anyone else: use the old email (as that is still the current one)

**Comment by scottwyn13** [comment] 2024-04-01 20:37
I believe the issue is with the type "email_change". According to Supabase docs it states that the type should be "email_change" but rather "emailChange".
![Screenshot 2024-04-01 at 1 37 01 PM](https://github.com/supabase/auth-js/assets/139585731/4762c04f-370b-4e00-9ca8-ca6754b216b3)

**Comment by kangmingtay** [comment] 2024-05-07 08:45
@scottwyn13 it should be `email_change` as defined in the types here - https://github.com/supabase/auth-js/blob/64a926c2415f2bb6d9da52871c5bfe7bfd7c0eac/src/lib/types.ts#L650 

closing since i'm unable to reproduce this error

**Closed by kangmingtay** 2024-05-07 08:45 UTC
Labels: bug
