### ISSUE TITLE
Invalid parameter value for code_challenge_method: 's256' with PCKE & Google

### ISSUE THREAD

**Issue by imownbey** [supabase/auth-js#770] opened 2023-04-24 20:33 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Trying to use the new pkce auth flow with Google sign in based on the blog post: 
https://supabase.com/blog/supabase-auth-sso-pkce#server-side-and-mobile-auth
I get the following error when showing the google login screen:
```
Invalid parameter value for code_challenge_method: 's256' is not a valid CodeChallengeMethod [Learn more about this error](https://developers.google.com/identity/protocols/oauth2)

Error 400: invalid_request
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by colestriler** [comment] 2023-09-05 15:24
I'm also running into this. @imownbey were you able to find a workaround?

**Comment by colestriler** [comment] 2023-09-05 15:44
Also running into this. I downgraded my version of `@supabase/auth-helpers-nextjs` and that fixed it.

**Comment by kangmingtay** [comment] 2023-09-05 18:11
@colestriler can you elaborate on the steps taken to reproduce this please? are you using the `signInWithOAuth` method?

**Comment by colestriler** [comment] 2023-09-05 21:01
@kangmingtay turns out downgrading did not totally fix the issue.

You can replicate the issue by cloning this repo https://github.com/silentworks/safari-vercel-test and trying to authenticate with Google on localhost (i.e. NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321). 

I posted in Discord earlier today and @silentworks said it's likely my Google console setup (https://discord.com/channels/839993398554656828/1148690630348906577/1148690630348906577).

I ended up deploying the app with the same Google console keys to test if it was only an issue on localhost, and it works fine on prod.

<img width="539" alt="blocked" src="https://github.com/supabase/gotrue-js/assets/66885708/800b81c3-aba0-42fe-adde-83a5c06d15a7">

**Comment by kangmingtay** [comment] 2023-09-12 04:47
hey @colestriler, can you please reach out to us through support (https://supabase.com/dashboard/support/new) - it will be easier to investigate if we have your project ref / ask for more sensitive information pertaining to your setup.

**Comment by kn** [comment] 2023-09-27 03:50
Having the same issue here as well with local supabase DB.

I haven't investigated deeply but if the library really meant to pass `code_challenge_method` as `s256`, I think it can be case sensitive, i.e., should be `S256`. Indeed, if I change the value to upper case, it works for me.

**Comment by patrikengborg** [comment] 2023-10-02 06:40
Same problem here, and it works if I change "s256" to "S256" in the query string.

**Comment by OlegGulevskyy** [comment] 2023-11-04 16:36
I don't understand where to make this change and how?

**Comment by sroussey** [comment] 2023-11-16 02:22
https://github.com/search?q=repo%3Asupabase%2Fgotrue-js+s256&type=code

**Comment by sroussey** [comment] 2023-11-16 16:33
Test case https://github.com/sroussey/test-supabase

**Comment by J0** [comment] 2023-12-20 07:02
Hey team,

Thanks for reporting the issue and for supplying a test repository - I'm not able to replicate this issue though - [this](https://share.cleanshot.com/jk78vz16) is what it looks like on my end.

The code_challenge_method param is intended for Supabase Auth and not for Google. There was a known issue in April where the code_challenge_method param was not sanitized which lead to the error. It was patched in late April/early May and we haven't observed repeat instances since then

Could I trouble you to try clearing both package-lock.json and node_modules and reinstalling after?

Alternatively, if there's a staging environment or another test repository where we can replicate this we can take a look further.

Let us know

Thanks!

**Comment by sroussey** [comment] 2023-12-22 22:10
I never use `npx supabase start/stop` so it never updates (I start and stop docker instead). I imagine many people do this.

While the bug was fixed long ago, it was not fixed in my local dev since my local supabase never updated.

**Comment by J0** [comment] 2024-06-17 09:32
Hey team,

Going to close the issue as it should be fixed in the latest update but feel free to re-open if it persists for you

**Closed by J0** 2024-06-17 09:32 UTC
Labels: bug
